[tox]
envlist = py39
minversion = 3.7
skipsdist = True
skip_missing_interpreters = true

[testenv]
skip_install = True
deps =
    -r docker/test-requirements.txt
commands_pre = python -m pip install --no-build-isolation -e .
commands = python -m pytest -v tests
norecursedirs = .tox

[testenv:docs]
commands_pre =
deps = .[doc]
commands = python setup.py build_sphinx -W
